%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% m_trace_transform_path_translate.m
% 
% Utility function that is designed to allow for simple geometric
% transformations of paths in the data format generated by p_svg_raytracer
% and p_get_svg_data. Rotation is an angle in radians. If the rotation
% point is empty, then the object centroid is used.
% 
% INPUTS:
%   path    Axis UserData struct passed by p_svg_raytracer.
%   offset  2-vector [x, y] used for relative translation of path
% 
% Patrick Kilcullen
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


function path_out = m_trace_transform_path_translate(path, offset)
    dx = offset(1);
    dy = offset(2);
    M = [1, 0, dx; 0, 1, dy; 0, 0, 1];
    path_out = m_trace_transform_path_matrix(path, M);
end

