%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% m_trace_transform_path_rotate.m
% 
% Utility function that is designed to allow for simple geometric
% transformations of paths in the data format generated by p_svg_raytracer
% and p_get_svg_data. Rotation is an angle in radians. If the rotation
% point is empty, then the object centroid is used.
% 
% INPUTS:
%   path    Axis UserData struct passed by p_svg_raytracer.
%   angle   Rotation angle in radians.
%   center  center point [x, y]. Centroid is used if empty.
% Patrick Kilcullen
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


function path_out = m_trace_transform_path_rotate(path, angle, center)
    
    if isempty(center)
        center = m_trace_get_path_graphics_centroid(path);
    end

    cx = center(1);
    cy = center(2);
    dt = angle;

    M1 = [      1,        0, -cx;       0,       1, -cy; 0, 0, 1];
    M2 = [cos(dt), -sin(dt),   0; sin(dt), cos(dt),   0; 0, 0, 1];
    M3 = [      1,        0, +cx;       0,       1, +cy; 0, 0, 1];
    M = M3 * M2 * M1;     % 3x3 transformation matrix (i.e. homography)
    
    path_out = m_trace_transform_path_matrix(path, M);
end

